In [1]:
import os
os.getcwd()

'C:\\Users\\91934'

In [3]:
os.listdir()

['.bash_history',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.eclipse',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.p2',
 '.vscode',
 '1.ipynb',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'day1.ipynb',
 'day11.ipynb',
 'day15.ipynb',
 'day16.ipynb',
 'day17.ipynb',
 'day18.ipynb',
 'day2.ipynb',
 'day3 tasks.ipynb',
 'day3.ipynb',
 'day5 matplot.ipynb',
 'day8.ipynb',
 'day9.ipynb',
 'Documents',
 'Downloads',
 'eclipse',
 'eclipse-workspace',
 'Employee Salary Prediction.ipynb',
 'Favorites',
 'index.ipynb',
 'IntelGraphicsProfiles',
 'ipl_analysis_report.csv',
 'Links',
 'Local Settings',
 'ML-1.ipynb',
 'ML_DAT.ipynb',
 'Multiple linaer regression.ipynb',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'player_runs_chart.png',
 'practice1.ipynb',
 'practice2.ipynb',
 'PrintHood',
 'pythonlab1.ipynb',
 'pythonlab2.ipynb',
 'pythonlab3.ipynb',
 'pythonlab4.ipynb',
 'Recent',
 'Saved Games',
 'Searches',
 'season_comparison_chart.png',
 'SendTo',
 'Simple_linear_regression.ipynb',
 'source',
 'Start Menu',
 'strike_rate_chart.png',
 'team_wins_chart.png',
 'Templates',
 'untitled',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'Untitled10.ipynb',
 'Untitled11.ipynb',
 'Untitled12.ipynb',
 'Untitled13.ipynb',
 'Untitled14.ipynb',
 'Untitled15.ipynb',
 'Untitled16.ipynb',
 'Untitled17.ipynb',
 'Untitled18.ipynb',
 'Untitled19.ipynb',
 'Untitled2.ipynb',
 'Untitled20.ipynb',
 'Untitled21.ipynb',
 'Untitled22.ipynb',
 'Untitled23.ipynb',
 'Untitled24.ipynb',
 'Untitled25.ipynb',
 'Untitled26.ipynb',
 'Untitled27.ipynb',
 'Untitled28.ipynb',
 'Untitled29.ipynb',
 'Untitled3.ipynb',
 'Untitled30.ipynb',
 'Untitled31.ipynb',
 'Untitled32.ipynb',
 'Untitled33.ipynb',
 'Untitled34.ipynb',
 'Untitled35.ipynb',
 'Untitled36.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Untitled9.ipynb',
 'Videos']

In [3]:
import pandas as pd
df = pd.read_excel(r"C:\Users\91934\OneDrive\Documents\Kethan\Data Science\Projet\indian-job-market-dataset-2025.xlsx")
df.head()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0

In [4]:
df

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97924,"CNC Machine Maintenance Engineer @ Manali, Che...",270925008790,INR,6 Days Ago,GSH Group,"CNC Maintenance,CNC Machines,Electrical Mainte...",2-5 Yrs,"50,000-2 Lacs PA","Chennai, Thiruvallur",938550,284.0,4.2,Experience: Minimum 2+ Years in CNC Machine El...,50000.0,200000.0,2.0,5.0
97925,IT Cum Digital Marketing Executive,270925008668,INR,6 Days Ago,Luxus Green Mobility Pvt. Ltd.,"Google AdWords,Digital Marketing,Social Media ...",1-2 Yrs,Not disclosed,Bilaspur,123904985,13.0,2.6,<p> </p><p><strong>Position Overview :-</stron...,0.0,0.0,1.0,2.0
97926,Senior Research Associate,270925008467,INR,6 Days Ago,Cadila Pharmaceuticals,"Analytical Method Validation,Analytical Method...",4-9 Yrs,Not disclosed,Ahmedabad,14957,2134.0,3.4,Documentation as per GLP requirement,0.0,0.0,4.0,9.0
97927,Customer Care Associate,270925008099,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Strong Communica...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Zirakpur",123804403,NaN,NaN,Job title-Customer Care Associate\nJob locatio...,70000.0,200000.0,0.0,3.0
97928,Client Relationship Executive,270925008094,INR,6 Days Ago,Logon Global Solutions,"Client Support,English,Client Coordination,Mal...",0-3 Yrs,1.92-3.36 Lacs PA,Kochi(Kakkanad),125008981,4.0,4.2,<p> <strong>Role:</strong> Primary advisor for...,192000.0,336000.0,0.0,3.0

In [5]:
df.shape

(97929, 17)

In [6]:
df.columns.tolist()

['title',
 'jobId',
 'currency',
 'jobUploaded',
 'companyName',
 'tagsAndSkills',
 'experience',
 'salary',
 'location',
 'companyId',
 'ReviewsCount',
 'AggregateRating',
 'jobDescription',
 'minimumSalary',
 'maximumSalary',
 'minimumExperience',
 'maximumExperience']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  object
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  object
 3   jobUploaded        97929 non-null  object
 4   companyName        97925 non-null  object
 5   tagsAndSkills      97358 non-null  object
 6   experience         95824 non-null  object
 7   salary             97929 non-null  object
 8   location           97929 non-null  object
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  object
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), object(9)
memory usage: 12.7+ MB

In [8]:
df.isnull().sum()

title                    0
jobId                    0
currency                 0
jobUploaded              0
companyName              4
tagsAndSkills          571
experience            2105
salary                   0
location                 0
companyId                0
ReviewsCount         35252
AggregateRating      35252
jobDescription           0
minimumSalary          571
maximumSalary          571
minimumExperience      571
maximumExperience      571
dtype: int64

In [7]:
for column in df.columns:
    print("\n", column)
    print(df[column].nunique())

 title
55104

 jobId
97679

 currency
2

 jobUploaded
30

 companyName
18668

 tagsAndSkills
84307

 experience
287

 salary
1339

 location
10066

 companyId
18328

 ReviewsCount
1375

 AggregateRating
41

 jobDescription
80679

 minimumSalary
164

 maximumSalary
204

 minimumExperience
31

 maximumExperience
33

In [10]:
df.duplicated().sum()

247

In [11]:
df.columns.tolist()

['title',
 'jobId',
 'currency',
 'jobUploaded',
 'companyName',
 'tagsAndSkills',
 'experience',
 'salary',
 'location',
 'companyId',
 'ReviewsCount',
 'AggregateRating',
 'jobDescription',
 'minimumSalary',
 'maximumSalary',
 'minimumExperience',
 'maximumExperience']

In [12]:
df.duplicated().sum()

247

In [8]:
# Create a copy for cleaning
df_clean = df.copy()

In [9]:
df_clean.head()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0

In [10]:
# Clean column names
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df_clean.columns.tolist()

['title',
 'jobid',
 'currency',
 'jobuploaded',
 'companyname',
 'tagsandskills',
 'experience',
 'salary',
 'location',
 'companyid',
 'reviewscount',
 'aggregaterating',
 'jobdescription',
 'minimumsalary',
 'maximumsalary',
 'minimumexperience',
 'maximumexperience']

In [8]:
df_clean.duplicated().sum()

247

In [11]:
df_clean = df_clean.drop_duplicates()

In [12]:
print("Duplicates after cleaning:", df_clean.duplicated().sum())
print("New dataset shape:", df_clean.shape)

Duplicates after cleaning: 0
New dataset shape: (97682, 17)

In [13]:
df_clean.isnull().sum()

title                    0
jobid                    0
currency                 0
jobuploaded              0
companyname              4
tagsandskills          571
experience            2102
salary                   0
location                 0
companyid                0
reviewscount         35165
aggregaterating      35165
jobdescription           0
minimumsalary          571
maximumsalary          571
minimumexperience      571
maximumexperience      571
dtype: int64

In [14]:
df_clean = df_clean.dropna(subset=['companyname'])

In [15]:
df_clean['tagsandskills'] = df_clean['tagsandskills'].fillna('Not Specified')

In [16]:
columns_to_fill = [
    'minimumsalary',
    'maximumsalary',
    'minimumexperience',
    'maximumexperience'
]

df_clean[columns_to_fill] = df_clean[columns_to_fill].fillna(0)

In [17]:
df_clean['reviewscount'] = df_clean['reviewscount'].fillna(0)
df_clean['aggregaterating'] = df_clean['aggregaterating'].fillna(0)

In [18]:
df_clean.isnull().sum()

title                   0
jobid                   0
currency                0
jobuploaded             0
companyname             0
tagsandskills           0
experience           2102
salary                  0
location                0
companyid               0
reviewscount            0
aggregaterating         0
jobdescription          0
minimumsalary           0
maximumsalary           0
minimumexperience       0
maximumexperience       0
dtype: int64

In [19]:
df_clean.shape

(97678, 17)

In [20]:
df_clean['experience'].value_counts().head(20)

5-10 Yrs     6433
3-8 Yrs      5746
1-3 Yrs      3904
2-5 Yrs      3767
1-6 Yrs      3620
2-7 Yrs      3606
0-5 Yrs      3286
3-5 Yrs      3283
5-8 Yrs      3264
4-9 Yrs      2868
1-5 Yrs      2860
0-1 Yrs      2579
1-4 Yrs      2418
6-11 Yrs     2378
0-2 Yrs      2299
2-4 Yrs      2262
7-12 Yrs     2196
8-13 Yrs     2126
3-6 Yrs      2124
15-20 Yrs    1949
Name: experience, dtype: int64

In [21]:
df_clean['experience'] = df_clean['experience'].fillna('Not Specified')

In [22]:
df_clean.isnull().sum()

title                0
jobid                0
currency             0
jobuploaded          0
companyname          0
tagsandskills        0
experience           0
salary               0
location             0
companyid            0
reviewscount         0
aggregaterating      0
jobdescription       0
minimumsalary        0
maximumsalary        0
minimumexperience    0
maximumexperience    0
dtype: int64

In [21]:
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])

Rows: 97678
Columns: 17

In [23]:
text_columns = [
    'title',
    'currency',
    'companyname',
    'tagsandskills',
    'experience',
    'location',
    'jobdescription'
]

for col in text_columns:
    df_clean[col] = df_clean[col].astype(str).str.strip()

In [23]:
df_clean.head()

,title,jobid,currency,jobuploaded,companyname,tagsandskills,experience,salary,location,companyid,reviewscount,aggregaterating,jobdescription,minimumsalary,maximumsalary,minimumexperience,maximumexperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,0.0,0.0,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,0.0,0.0,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0

In [24]:
df_clean['currency'] = df_clean['currency'].str.upper()
df_clean['location'] = df_clean['location'].str.title()
df_clean['companyname'] = df_clean['companyname'].str.strip()

In [25]:
print(df_clean[['title', 'companyname', 'location', 'currency']].head(10))

                                         title  \
0                    Sr. HR Recruiter (NON IT)
1                      Fire And Safety Officer
2  Opening For Performance Marketing - Chennai
3                    Medical Billing Executive
4  Senior Group Product Manager -  CNS Therapy
5                            Senior Accountant
6                       Maintenance Technician
7                   Officer/Engineer Technical
8                       Officer- Technical Lab
9                    Site Reliability Engineer

                                         companyname  \
0                                              Orion
1  Apollo Hospitals International Limited, Ahmedabad
2                            TVS Credit Services Ltd
3                                GNR Global Services
4                             Cadila Pharmaceuticals
5                                 Vedaant Techno Art
6                                Avalon Technologies
7                        Balkrishna Industries (BKT)
8                        Balkrishna Industries (BKT)
9                                            Coforge

                               location currency
0                  Kolkata(Chinar Park)      INR
1                Gandhinagar, Ahmedabad      INR
2                               Chennai      INR
3  Mohali, Chandigarh, Kharar, Zirakpur      INR
4                             Ahmedabad      INR
5                  Noida, Greater Noida      INR
6   Sriperumbudur, Chennai, Kanchipuram      INR
7                     Aurangabad(Waluj)      INR
8                     Aurangabad(Waluj)      INR
9    New Delhi, Gurugram, Greater Noida      INR

In [26]:
df_clean.dtypes

title                 object
jobid                  int64
currency              object
jobuploaded           object
companyname           object
tagsandskills         object
experience            object
salary                object
location              object
companyid              int64
reviewscount         float64
aggregaterating      float64
jobdescription        object
minimumsalary        float64
maximumsalary        float64
minimumexperience    float64
maximumexperience    float64
dtype: object

In [26]:
df_clean['jobuploaded'].head()

0    6 Days Ago
1    6 Days Ago
2    6 Days Ago
3    6 Days Ago
4    6 Days Ago
Name: jobuploaded, dtype: object

In [27]:
df_clean['jobuploaded'] = pd.to_datetime(
    df_clean['jobuploaded'],
    errors='coerce'
)

In [29]:
df_clean['jobuploaded'].head()
df_clean['jobuploaded'].dtype

dtype('<M8[ns]')

In [30]:
df_clean[['salary', 'minimumsalary', 'maximumsalary']].dtypes

salary            object
minimumsalary    float64
maximumsalary    float64
dtype: object

In [28]:
df_clean[['salary', 'minimumsalary', 'maximumsalary']].head(10)

             salary  minimumsalary  maximumsalary
0       2-4 Lacs PA       200000.0       400000.0
1       3-5 Lacs PA       300000.0       500000.0
2     Not disclosed            0.0            0.0
3  70,000-2 Lacs PA        70000.0       200000.0
4      8-18 Lacs PA       800000.0      1800000.0
5     3.5-6 Lacs PA       350000.0       600000.0
6     Not disclosed            0.0            0.0
7     Not disclosed            0.0            0.0
8     Not disclosed            0.0            0.0
9     Not disclosed            0.0            0.0

In [32]:
df_clean[['experience', 'minimumexperience', 'maximumexperience']].head(10)

  experience  minimumexperience  maximumexperience
0    2-4 Yrs                2.0                4.0
1   6-11 Yrs                6.0               11.0
2  12-18 Yrs               12.0               18.0
3    0-3 Yrs                0.0                3.0
4   5-10 Yrs                5.0               10.0
5  10-15 Yrs               10.0               15.0
6    3-5 Yrs                3.0                5.0
7    2-3 Yrs                2.0                3.0
8    2-4 Yrs                2.0                4.0
9   4-14 Yrs                4.0               14.0

In [33]:
df_clean['jobuploaded'] = pd.to_datetime(
    df_clean['jobuploaded'],
    errors='coerce'
)

In [34]:
print(df_clean['jobuploaded'].head())
print(df_clean['jobuploaded'].dtype)

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: jobuploaded, dtype: datetime64[ns]
datetime64[ns]

In [35]:
print(df_clean['jobuploaded'].isnull().sum())

97678

In [37]:
df['jobUploaded'].head(10)

0    6 Days Ago
1    6 Days Ago
2    6 Days Ago
3    6 Days Ago
4    6 Days Ago
5    6 Days Ago
6    6 Days Ago
7    6 Days Ago
8    6 Days Ago
9    6 Days Ago
Name: jobUploaded, dtype: object

In [45]:
print(df.columns.tolist())

['title', 'jobId', 'currency', 'jobUploaded', 'companyName', 'tagsAndSkills', 'experience', 'salary', 'location', 'companyId', 'ReviewsCount', 'AggregateRating', 'jobDescription', 'minimumSalary', 'maximumSalary', 'minimumExperience', 'maximumExperience']

In [ ]:
df['jobUploaded'].head(10)

In [39]:
df['jobUploaded'].head(10)

0    6 Days Ago
1    6 Days Ago
2    6 Days Ago
3    6 Days Ago
4    6 Days Ago
5    6 Days Ago
6    6 Days Ago
7    6 Days Ago
8    6 Days Ago
9    6 Days Ago
Name: jobUploaded, dtype: object

In [40]:
df_clean['jobuploaded'] = df['jobUploaded']

In [41]:
df_clean['jobuploaded'].head(10)

0    6 Days Ago
1    6 Days Ago
2    6 Days Ago
3    6 Days Ago
4    6 Days Ago
5    6 Days Ago
6    6 Days Ago
7    6 Days Ago
8    6 Days Ago
9    6 Days Ago
Name: jobuploaded, dtype: object

In [29]:
df_clean['jobuploaded'].value_counts().head(20)

Series([], Name: jobuploaded, dtype: int64)

In [44]:
import numpy as np

df_clean['days_since_posted'] = (
    df_clean['jobuploaded']
    .str.extract(r'(\d+)')[0]
    .astype(float)
)

In [52]:
df_clean[['jobuploaded', 'days_since_posted']].head(10)

  jobuploaded  days_since_posted
0  6 Days Ago                6.0
1  6 Days Ago                6.0
2  6 Days Ago                6.0
3  6 Days Ago                6.0
4  6 Days Ago                6.0
5  6 Days Ago                6.0
6  6 Days Ago                6.0
7  6 Days Ago                6.0
8  6 Days Ago                6.0
9  6 Days Ago                6.0

In [45]:
df_clean[['salary', 'minimumsalary', 'maximumsalary']].head(10)

             salary  minimumsalary  maximumsalary
0       2-4 Lacs PA       200000.0       400000.0
1       3-5 Lacs PA       300000.0       500000.0
2     Not disclosed            0.0            0.0
3  70,000-2 Lacs PA        70000.0       200000.0
4      8-18 Lacs PA       800000.0      1800000.0
5     3.5-6 Lacs PA       350000.0       600000.0
6     Not disclosed            0.0            0.0
7     Not disclosed            0.0            0.0
8     Not disclosed            0.0            0.0
9     Not disclosed            0.0            0.0

In [46]:
df_clean[['salary', 'minimumsalary', 'maximumsalary']].dtypes

salary            object
minimumsalary    float64
maximumsalary    float64
dtype: object

In [47]:
df_clean['salary'].value_counts().head(20)

Not disclosed       63917
3-5 Lacs PA           584
3-6 Lacs PA           549
3-4 Lacs PA           494
2-3 Lacs PA           470
2-4 Lacs PA           434
4-6 Lacs PA           434
10-20 Lacs PA         380
15-25 Lacs PA         378
3-4.5 Lacs PA         373
2.5-4 Lacs PA         353
2.5-3.5 Lacs PA       338
Unpaid                333
2-3.5 Lacs PA         290
3-3.5 Lacs PA         267
3-8 Lacs PA           266
50,000-3 Lacs PA      265
2-2.5 Lacs PA         261
2-5 Lacs PA           258
1-3 Lacs PA           252
Name: salary, dtype: int64

In [48]:
df_clean['average_salary'] = (
    df_clean['minimumsalary'] + df_clean['maximumsalary']
) / 2

In [49]:
df_clean[
    ['minimumsalary', 'maximumsalary', 'average_salary']
].head(10)

   minimumsalary  maximumsalary  average_salary
0       200000.0       400000.0        300000.0
1       300000.0       500000.0        400000.0
2            0.0            0.0             0.0
3        70000.0       200000.0        135000.0
4       800000.0      1800000.0       1300000.0
5       350000.0       600000.0        475000.0
6            0.0            0.0             0.0
7            0.0            0.0             0.0
8            0.0            0.0             0.0
9            0.0            0.0             0.0

In [30]:
df_clean.to_excel(
    "cleaned_indian_job_market_data.xlsx",
    index=False
)

In [31]:
import os

print(os.path.abspath("cleaned_indian_job_market_data.xlsx"))

C:\Users\91934\cleaned_indian_job_market_data.xlsx